### ISSUE TITLE
Unable to get data from champion select

### ISSUE THREAD

**Issue by LucasMcManus** [meraki-analytics/orianna#103]
Hi, the title really says it all. I was wondering if this was possible with Orianna, I've looked through the documentation and I can't seem to find it. Am I just missing something obvious?

**Comment by jjmaldonis** [comment]
Hey, you're not missing anything. The Riot API doesn't provide info about champ-select. It only provides post-match information. If you only care about accessing your own champ-select info, you can use the LCU API. If you want to do that, jump onto the Riot API Discord and look in the pinned messages in the #lcu-api channel.

**Comment by LucasMcManus** [comment]
Thank you very much, sorry to bother you guys since this isnt part of your
project though!

**Comment by jjmaldonis** [comment]
No worries!

**Comment by robrua** [comment]
Just wanted to note here - Jason's talking about if you're looking for _live_ pick/ban data, which you have to use the LCU API for.

If you're just looking for the pick order and bans from each team for a historical match, you can get a `Team` object using `match.getRedTeam()` or `match.getBlueTeam()`. You can do `team.getBans()` to check their bans, or `team.getParticipants()` to get a list of the members of the team in pick order (which will include what champion they chose using `participant.getChampion()`.
