### ISSUE TITLE
Bug when fetching match history with start time

### ISSUE THREAD

**Issue by fastboyz** [meraki-analytics/orianna#106]
When fetching the match list like this 
` Orianna.matchHistoryForSummoner(summoner).withStartTime(seasonStartTime)
          .withQueues(Constants.getQeuesList()).get()` it will start collection just fine but after a while it will throw a bad request. upon inspecting the request causing the error, we can see that there is one request where there is a request with startTime and endTime, and the endtime is lower than the startTime.
the LOG can be found here: https://gist.github.com/fastboyz/fc7a466348c2bdd1cfea68f7ee420095
the code sample here: https://gist.github.com/fastboyz/e69cf37fa8cd72f5d0334a26a0add3f7

**Comment by robrua** [comment]
This should be fixed by 3154c3bc
