### ISSUE TITLE
Frame.getParticipantFrames() returns an incorrect map

### ISSUE THREAD

**Issue by WTIMJK** [meraki-analytics/orianna#110]
First off, I'm using Orianna-4.0.0-rc5-jar-with-dependencies.jar
The Frame class's getParticipantFrames() method is not mapping participants to their appropriate frame. After a while I did figure out what it maps to though...
getParticipantFrames() returns a Map<Participant, ParticipantFrame> object but the mapping is not by participantId, which is expected. Participant #1 should get frames for their character. It is instead mapped to the order in which the participants appear in the raw json from Riot. The only way participant #1's frame would be mapped correctly is if participant #1's frame was first in the participantFrames collection.
Riot's JSON contains a participantId in each participantFrame to show who the data belongs to, but Orianna does not do this, which would be fine if the Participant -> ParticipantFrame mapping was correct. I have reviewed the location data on frame 0 for two different games using Orianna and mapped them by hand using Riot API output to verify. I have documented this in the attached excel file to try to help convey what I'm talking about. The pattern holds true for these two games.
In the second game, participant 10 happened to also be the 10th ParticipantFrame, so their data was actually correct.
[ParticipantFrames.xlsx](https://github.com/meraki-analytics/orianna/files/3797494/ParticipantFrames.xlsx)

If you look at the first tab in this excel, you will see two tables, on with data from Riot's API and one from Orianna. Orianna says that the Sejuani player's coordinates at the game's start are (311,649), but these are actually lulu's coordinates. Sejuani is participant 5, and lulu is the 5th player in the collection of ParticipantFrames, so Orianna mistakenly grabs lulu's data it seems. This pattern continues and is repeated in the other game (tab 2) as well which shows this was not a one-off issue.

**Comment by robrua** [comment]
Hey, thanks for the detailed information in the issue. This has been fixed in 7e70522.

The keys of the participant frame matching used to be the same participantId given in the value it references. Not sure when they changed that, but it's not using the ID listed in the value instead of the key.
