### ISSUE TITLE
`Translation` has `updated_at` field instead of `heading`

### ISSUE THREAD

**Issue by MingweiSamuel** [meraki-analytics/orianna#113]
https://github.com/RiotGames/developer-relations/issues/79

There is currently a bug in the docs that show that `Translation` should have a `updated_at` field, so Orianna tries to parse as a date and fails with NPE. The field doesn't exist and should be `heading` instead

https://github.com/meraki-analytics/orianna/blob/1cd238af9534b9b719a1073fd84572b5005157e7/orianna/src/main/java/com/merakianalytics/orianna/types/dto/status/Translation.java#L63-L68

**Comment by robrua** [comment]
Fixed this in d0fbc6d.

Thanks for the report!
