### ISSUE TITLE
IllegalArgumentException: Can't get key for League without ID or queue and tier!

### ISSUE THREAD

**Issue by Jay-ArBrouillard** [meraki-analytics/orianna#117]
Bug: Default code given doesn't work. I removed my api key in the image for obvious and my api key is confirmed to be working. Orianna.challengerLeagueInQueue(Queue.RANKED_SOLO).get(); //Throwing the error

![image](https://user-images.githubusercontent.com/44123272/79083307-2356a700-7cf3-11ea-8996-4789b76a5bdc.png)

**Comment by robrua** [comment]
Hey, what version of orianna are you using & how are you pulling it in as a dependency? If you're not already, can you try using the latest SNAPSHOT and tell me if you're still seeing the same problem? I can't reproduce it.

**Comment by Jay-ArBrouillard** [comment]
Thanks for the reply, but i've since move to a different api. But I used this in my gradle: 

```
repositories {
  mavenCentral()
}

dependencies {
  implementation "com.merakianalytics.orianna:orianna:4.0.0-rc5"
}
```

**Comment by robrua** [comment]
Alright, thanks for the report though. For anyone following along, this should be working in the latest SNAPSHOT and we'll get a release out soon to make sure it's working in the stable version as well.
