### ISSUE TITLE
Summoner unraked error

### ISSUE THREAD

**Issue by JustinSGD** [meraki-analytics/orianna#126]
final LeagueEntry rankedFivesEntries = summoner.getLeaguePosition(Queue.RANKED_SOLO);
After that, nothing happens once the player is unranked. The complete code crashes.

**Comment by robrua** [comment]
Is your code crashing while executing that call or after?  When the summoner isn't ranked that code should return `null`, which you'll want to check for to make sure you don't run into a NullPointerException.

**Comment by JustinSGD** [comment]
This is my code.

**Comment by robrua** [comment]
Yeah, this looks to me like there's going to be a NullPointerException on line 41 when the summoner isn't ranked. Line 37 will return `null`, which you should check before trying to use it.
