### ISSUE TITLE
Latest release doesn't include Nexus Blitz

### ISSUE THREAD

**Issue by ACSchott526** [meraki-analytics/orianna#129]
`orianna/src/main/java/com/merakianalytics/orianna/types/common/Queue.java` doesn't include `NEXUS_BLITZ(1300, "NEXUS_BLITZ")` in the latest release `4.0.0-rc7`

Are there any plans to cut a new release soon?

**Comment by ACSchott526** [comment]
cc @robrua

**Comment by robrua** [comment]
New release should be available now

**Comment by ACSchott526** [comment]
Thanks for the quick turnaround!
