### ISSUE TITLE
Item 2004 (mana pot?)

### ISSUE THREAD

**Issue by knezzz** [meraki-analytics/Orianna#47]
com.robrua.orianna.type.exception.APIException: A NOT_FOUND (404) error was received from the server for URI https://global.api.pvp.net/api/lol/static-data/eune/v1.2/item/2004?MYAPIKEYWASHERE

**Comment by robrua** [comment]
Added to the list of ignored items https://github.com/meraki-analytics/Orianna/commit/d322fd58f52190c627c99492c725cb1e9b065362
