### ISSUE TITLE
Getting drakes and nashors data from ID Match

### ISSUE THREAD

**Issue by Nithmen** [meraki-analytics/Orianna#48]
Good morning, last version of Orianna I used to get the time of the drakes and the nahors of a match i couldn't do it properly. I'm doing by the match.getTimeline().getFrames().get(j).getEvents().get(i).getParticipant().getTeam()  method but the problem is I get the time, the monster type but not the team, it appears null. Would this be fixed on new version?

Thanks.

**Comment by robrua** [comment]
Hey - I assume that you're trying to get which team killed the dragons/barons? In this case you should use `match.getTimeline().getFrames().get(j).getEvents().get(i).getKiller().getTeam()` instead, and you should get the right value.

This shouldn't have been affected by any recent changes, so it'll likely work on whatever version you're using (though I do recommend always using as recent a version as you can).

**Comment by Nithmen** [comment]
Okay, i actually love you more than ever.
Thanks m8!

**Comment by robrua** [comment]
No problem
