### ISSUE TITLE
New type of drakes.

### ISSUE THREAD

**Issue by Nithmen** [meraki-analytics/orianna#54]
Good morning, you uploaded the new version of Orianna like 2 weeks ago. Does it have the new update of the new type of dragons? If not, will you upload it soon? I'm wondering if the API would
differentiate the diferents types of dragons.

Thanks.

**Comment by robrua** [comment]
Hey - sorry for the late reply on this. Been busy lately. According to [this thread](https://developer.riotgames.com/discussion/community-discussion/show/3E3aMrG2) on the Riot forums, the API support for this will be available eventually, and Ori will support it when that happens.
