### ISSUE TITLE
IllegalArgumentException for Siege when calling RiotAPI.getStats(long id)

### ISSUE THREAD

**Issue by jakewebber** [meraki-analytics/Orianna#58]
I am only getting this exception with certain summoners (tried on summoner name "silent moon"). 
Could this be caused by not having any siege games?
```
java.lang.IllegalArgumentException: No enum constant com.robrua.orianna.type.core.stats.PlayerStatsSummaryType.Siege

at java.lang.Enum.valueOf(Unknown Source)
at com.robrua.orianna.type.core.stats.PlayerStatsSummaryType.valueOf(PlayerStatsSummaryType.java:3)
at com.robrua.orianna.api.core.StatsAPI.getStats(StatsAPI.java:97)
at com.robrua.orianna.api.core.RiotAPI.getStats(RiotAPI.java:1779)

```

**Comment by robrua** [comment]
Hey, just fixed this in an update. You can get the latest snapshot .jar @ robrua.com/orianna and it'll be in all future releases.

**Comment by jakewebber** [comment]
Just got the latest snapshot 4.2.5, getting a new IllegalArgumentException: 
No enum constant com.robrua.orianna.type.core.stats.PlayerStatsSummaryType.RankedPremade3x3

**Comment by robrua** [comment]
Huh... They removed that one from the docs so I assumed they wouldn't be sending it anymore. It's added back in now.

**Comment by jakewebber** [comment]
Thanks for being on top of all this since the season change!
