### ISSUE TITLE
Debug Feature Request: Hide API key in URI prints and exception stack traces

### ISSUE THREAD

**Issue by jakewebber** [meraki-analytics/orianna#61]
I am using Orianna in a JavaFX application with Riot API calls built into the classes. I would like to leave stack trace printing in a public runnable release for debugging. Could an option be added to remove the api key from the end of printed URIs?

**Comment by robrua** [comment]
Hey,

This could be done, but I want to be careful with it for principle's sake. At what stage of your application is the API key getting set? If you're compiling your key into your application it can be easily compromised, regardless of whether it's being printed to console. If it's being added by the end-user at runtime, then (personally) I wouldn't see a problem having it be printed, as the only person seeing it is the one who put it there.

Can you go into a little more detail about how the API key is going to be provided for Ori in your current setup?

**Comment by jakewebber** [comment]
I set the API key in a separate non-cloneable, non-serializable, non-deserializable class with a public void method. This is the class's only function. All Riot API calls / Orianna are in their own class. 

I haven't looked too much into security...Would it be possible for someone to introduce a modified Orianna.jar that would just print the key? Any tips for keeping my key secured?
