### ISSUE TITLE
Deprecation of the v1/v2 endpoints

### ISSUE THREAD

**Issue by Hay1tsme** [meraki-analytics/orianna#66]
On June 24th, the v1/v2 endpoints will be deprecated for the new v3 ones

**Comment by jjmaldonis** [comment]
Yup, we have plans to update Orianna before then. It might not be for a couple months, but it will be before the depreciation period ends.

**Comment by Hay1tsme** [comment]
Awesome

**Comment by BWagener** [comment]
I really appreciate what you guys are doing!

**Comment by baribarton** [comment]
The v1/v2 endpoints were deprecated today. Has Orianna been updated accordingly?

**Comment by robrua** [comment]
Update on this: we've been grinding out the new Ori & Cass but ran into some details with the new architecture we found needed changing near the deadline. Coupled with some real life stuff getting in the way, we're a bit behind.

Sorry for the delay, but you can expect the new version of Ori with v3 support to be feature-complete in the next few days. Documentation/testing/etc. will follow shortly after.

Thanks for your patience,
Rob

**Comment by robrua** [comment]
Hey all, quick update on this.

I'm finally back to the grind on getting this out the door, and am looking to get it wrapped up soon. Feel free to pop in our [discord](https://discord.gg/MThwy9m) and bug me about it to incentivize me to hurry up, or if you have any questions or would like to help out. I'll be sure to alert you all when the initial 3.0.0 is ready to be used/tested.

**Comment by robrua** [comment]
Hey everybody, sorry for the ridiculous wait here. We're now in business with the v3 API and with the shiny new Orianna v3.0.0!
