### ISSUE TITLE
Invalid ClientID 512 - ClientJoinEvent

### ISSUE THREAD

**Issue by Tobias3107** [meraki-analytics/orianna#90]
Ignore this, Should be in another Project

**Comment by robrua** [comment]
Hey,

It looks like this is an issue with a chat bot you're building rather than an issue relating to Orianna. If it's about Orianna, can you give some details surrounding what you're doing with it and what issues your having?

**Comment by Tobias3107** [comment]
Oh sry. That should be in an other Project Issue ^^
