### ISSUE TITLE
Can I import this into a Scala IntelliJ Project?

### ISSUE THREAD

**Issue by Lockna** [meraki-analytics/orianna#97]
Am I able to import this into my IntelliJ Idea, where I program scala?

**Comment by robrua** [comment]
Sure - are you using any build tool to manage your dependencies like `sbt` or `maven` or `gradle`? If you're using `sbt` you can pull orianna from maven central as `libraryDependencies += "com.merakianalytics.orianna" % "orianna" % "4.0.0-rc3"`.

If you want the latest SNAPSHOT version you can add the sonatype maven snapshot repository as detailed [here](https://www.scala-sbt.org/1.x/docs/Library-Dependencies.html#Resolvers) then use `libraryDependencies += "com.merakianalytics.orianna" % "orianna" % "4.0.0-SNAPSHOT"` instead.
